### ISSUE TITLE
Stratum 0 fails stratum_to_text function

### ISSUE THREAD

**Issue by ilya-yarovoy** [cf-natali/ntplib#30]
https://github.com/cf-natali/ntplib/blob/08d0f7ef766715a52f472901de5e382c8f773855/ntplib.py#L456

When stratum is 0, the function fails with:
`TypeError: not all arguments converted during string formatting`

This is due to the assumption that stratum will always be 1

**Comment by cf-natali** [comment]
@ilya-yarovoy 

Thanks - this is actually already fixed by #16 .

Cheers,
