### ISSUE TITLE
`ntplib.ref_id_to_text(response.ref_id)` is not working correctly

### ISSUE THREAD

**Issue by beta-tester** [cf-natali/ntplib#35]
hi, i am using `ntplib-0.4.0` and wrote a little python3 script to 'scrape' the stratum one server from the list of [ntp.org StratumOneTimeServers](https://support.ntp.org//Servers/StratumOneTimeServers)
and test the listed hostnames with `ntplib` if they respond and 'identify' as statum 1 servers.

i have the issue that `ntplib.ref_id_to_text(response.ref_id)` always gives me an ip like dotted representation instead of a 4 letter word.
so `PPS` is translated to `80.83.83.0` and some other of the ref_id's that could be 4 letter words.

see the attached CSV filethe column `ref_id` was filled with the result of `ntplib.ref_id_to_text(response.ref_id)`:
[issue_ref_id.csv](https://github.com/cf-natali/ntplib/files/13853711/issue_ref_id.csv)

the construct `ntplib.ref_id_to_text(response.ref_id)` i took from the [pip example code snip](https://pypi.org/project/ntplib/)

**Comment by mahtin** [comment]
## The issue

It all stems from https://github.com/cf-natali/ntplib/blob/de3f0e62252481ce515ccc1ad786fd4c4c80b58e/ntplib.py#L484
More specifically, the fact that `NTP.REF_ID_TABLE` used here:
```
def ref_id_to_text(ref_id, stratum=2):
    """Convert a reference clock identifier to text according to its stratum.
...
    # return the result as a string or dot-formatted IP address
    if 0 <= stratum <= 1:
        text = "%c%c%c%c" % fields
        if text in NTP.REF_ID_TABLE:
            return NTP.REF_ID_TABLE[text]
```
The table does contain the string `PPS` (and `1PPS`). https://github.com/cf-natali/ntplib/blob/de3f0e62252481ce515ccc1ad786fd4c4c80b58e/ntplib.py#L60

So why does this not return anything? The answer is that there's code to check `if 0 <= stratum <= 1:` and the default stratum value to that function is `2`. Hence you need to call this via:
```
    value = ntplib.ref_id_to_text(response.ref_id, response.stratum)
```
I did that to the example code and all was fine after that!

So it looks like a one-line fix to the `README` is needed and is well worth a PR.

## However!

Looking at the `C` code for `ntp`, I see this [refid_str()](https://github.com/ntp-project/ntp/blob/9c75327c3796ff59ac648478cd4da8b205bceb77/libntp/numtoa.c#L38) which is called if the length of the buffer is less than or equal to 4 bytes long. See [dstadr_refid = refid_str(u32, 1);](https://github.com/ntp-project/ntp/blob/9c75327c3796ff59ac648478cd4da8b205bceb77/ntpq/ntpq-subs.c#L1687C17-L1687C17) code. All this combines to produce the `.PPS.` or `.GPS.` that you see in a pretty standard `ntpq -c peers` command.
```
$ ntpq -c peers europe.pool.ntp.org
     remote                                   refid      st t when poll reach   delay   offset   jitter
=======================================================================================================
*ntp1.time.einfra.hu                     .GPS.            1 u   42 1024  377    0.877   -0.209    0.422
+ntp2.time.einfra.hu                     .GPS.            1 u  618 1024  377    4.984    0.044    0.262
+ntp3.time.einfra.hu                     .GPS.            1 u   14 1024  377    0.663   -0.097    0.325
+ntp4.time.einfra.hu                     .GPS.            1 u    2 1024  377    0.492   -0.281    0.370
+ntp5.time.einfra.hu                     .GPS.            1 u  904 1024  377    3.469   -0.116    0.365
$
```
(yeah yeah - I was lucky to get a response - thank you to the folks in Hungary for having an open `ntpd` running).

I'm wondering if it's better to return that string vs the verbose present strings. (or maybe have a second function).

## One potential fix (now I look at the code)

The `ref_id_to_text()` function could emulate the `C` code a tad closer. It presently returns a string with null's at the end (not very Pythonic). That's a one line fix in the function.
```
        text = "%c%c%c%c" % fields.rstrip('\x00')
```
Then the `\0`'s get removed from NTP.REF_ID_TABLE. 
```
    REF_ID_TABLE = {
        "GOES":  "Geostationary Orbit Environment Satellite",
        "GPS": "Global Position System",
        "GAL": "Galileo Positioning System",
        "PPS": "Generic pulse-per-second",
...
}
```

That's also worth a PR.

**Comment by beta-tester** [comment]
> `    value = ntplib.ref_id_to_text(response.ref_id, response.stratum)`

oh, i have to provide the stratum value as well?!
that's what i missed.
the example on the pypi web page does not show that.
thanks.

but i don't like the long text representation.
i prefer the 4 letter representation.

so i came up with this code:
```
def ref_id_to_text4(ref_id, stratum):
    fields = (ref_id >> 24 & 0xff, ref_id >> 16 & 0xff,
          ref_id >> 8 & 0xff, ref_id & 0xff)
    if stratum == 1:
        is_text = True
        for f in fields:
            if not (
                ord('0') <= f <= ord('9') or
                ord('A') <= f <= ord('Z') or
                ord('a') <= f <= ord('z') or
                f in {ord(' '), ord('.'), ord(':'), ord(';'), ord(','), ord('-'), ord('_'), 0, }
                ):
                is_text = False
                break
    else:
        is_text = False
    if is_text:
        return ("%c%c%c%c" % fields).replace('\0',' ').strip()
    return "%d.%d.%d.%d" % fields
```
not nice, but for me its nice enough.
